### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by sergeyklay** [cronario/cronario#1]
Hello

First of all wanted to thank you for this amazing project.
Could you please write a little more detailed about releases? What's new, what's fixed etc.

![selection_002](https://cloud.githubusercontent.com/assets/1256298/10825645/a3a82ec0-7e6e-11e5-9a1e-efc36b569ec5.png)

**Comment by vlad-groznov** [comment]
Hi!

Thank you for your interest in the project
I will write a more detailed description for the releases.

Thank you, Sergey!
